# This is a config for E2B sandbox template.
# You can use template ID (pdyj8be7h3kbuwkl5w4u) or template name (vibe-template-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-template-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-template-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-template-1')

team_id = "b14e50f2-fb38-46aa-9353-b4f467dd3f20"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-template-1"
template_id = "pdyj8be7h3kbuwkl5w4u"
